#!groovy
// -*- mode: groovy -*-

def finalHook = {
  runStage('store CT logs') {
    archive '_build/test/logs/'
  }
}

build('{{name}}', 'docker-host', finalHook) {
  checkoutRepo()
  loadBuildUtils()

  runStage('load pipeline') {
    load("build_utils/jenkins_lib/setup.groovy")(["pipeErlangService"])
  }

  //Available options:
  //    pipeErlangService.runPipe(
  //        boolean testWithDependencies = true,
  //        boolean runInParallel = false,
  //        String pltHomeDir = 'default'
  //    )
  pipeErlangService.runPipe()
}
