#!groovy
// -*- mode: groovy -*-

def finalHook = {
  runStage('store CT logs') {
    archive '_build/test/logs/'
  }
}

build('{{name}}', 'docker-host', finalHook) {
  checkoutRepo()
  loadBuildUtils()

  def pipeErlangService
  runStage('load pipeline') {
    env.JENKINS_LIB = "build_utils/jenkins_lib"
    env.SH_TOOLS = "build_utils/sh"
    pipeErlangService = load("${env.JENKINS_LIB}/pipeErlangService.groovy")
  }

  //Available options:
  //    pipeErlangService.runPipe(
  //        boolean testWithDependencies = true,
  //        boolean runInParallel = false,
  //        String pltHomeDir = 'default'
  //    )
  pipeErlangService.runPipe()
}
