name: Check templates

on:
  push:
    branches:
      - 'master'
      - 'epic/**'
  pull_request:
    branches: [ '**' ]

jobs:
  check-library-template:
    name: Client Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add templates to rebar
        run: |
          mkdir -p ~/.config/rebar3/templates
          cp -rv ./* ~/.config/rebar3/templates

      - name: Generate library
        run: |
          rebar3 new erlang-library name=erlang_library

      - name: Update environment variables
        working-directory: erlang_library
        run: grep -v '^#' .env >> $GITHUB_ENV

      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}

      - name: Compile template output
        working-directory: erlang_library
        run: make compile

      - name: Check template output
        working-directory: erlang_library
        run: |
          make check-format
          make lint
          make xref
          make dialyze

      - name: Test template output
        working-directory: erlang_library
        run: |
          make test
          make cover

  check-service-template:
    name: Service Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add templates to rebar
        run: |
          mkdir -p ~/.config/rebar3/templates
          cp -rv ./* ~/.config/rebar3/templates

      - name: Generate service
        run: |
          rebar3 new erlang-service name=erlang_service

      - name: Update environment variables
        working-directory: erlang_service
        run: grep -v '^#' .env >> $GITHUB_ENV

      - name: Setup BEAM
        uses: erlef/setup-beam@v1.10
        with:
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}

      - name: Compile template output
        working-directory: erlang_service
        run: make compile

      - name: Check template output
        working-directory: erlang_service
        run: |
          make check-format
          make lint
          make xref
          make dialyze

      - name: Test template output
        working-directory: erlang_service
        run: |
          make test
          make cover
